apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: incidentmgmtappcap
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/incidentmgmtapp
  version:
    semver: v1.0.4
    allowRollback: true
  repository:
    url: incidents-mgmt-ocm.int.repositories.cloud.sap
    secretRef:
      name: acreds
  references:
    expand: true
  
