apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: incidentmgmtappcap
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/incidentmgmtapp
  version:
    semver: v1.0.6
    allowRollback: true
  repository:
    url:  github.com/sidhishruti22
    secretRef:
      name: acreds
  #serviceAccountName: air-gapped-ops    
  references:
    expand: true
   
  
