apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/ic-db
  provider:
    name: sidhishruti22
  version: v1.0.2
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.d9c3204310109d0cb4a85ef70e490fdfcc1b5da2edbd0d88836dc6732dda9188
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.0.2
  - access:
      imageReference: dcom-demo.int.repositories.cloud.sap/incidentmgmt-db-srv:latest
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.2
  - access:
      localReference: sha256.065c8905680f0836b5967c7793a4470cf5db94e90e113c42ab4700e5922d2e41
      mediaType: application/x-tgz
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.0.2
