apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/ic-app
  provider:
    name: sidhishruti22
  version: v1.0.6
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.2cd6efe46e8e280c77b2062730d0a290297dd67bca5792c22795f716324d39a8
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.0.6
  - access:
      imageReference: incidents-mgmt-dev.int.repositories.cloud.sap/incident-mgmt:0.0.0
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.2
  - access:
      localReference: sha256.3b90a138ac0e1aadb2f8bb3cdc745b3026c08678ca980bcd2f96f6d6cbd21672
      mediaType: application/x-tgz
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.0.6
