apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: incidentmgmtapp
  namespace: flux-system
spec:
  dependsOn:
  - name: ocm
    namespace: flux-system
  interval: 1m0s
  path: ./apps/incidentmgmtapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
